name: Test (on Ubuntu)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-projects:
          [
            ShiftManager.Common.Test,
            ShiftManager.Communication.InternalApi.Test,
            ShiftManager.Communication.RestApiBroker.Test,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Execute unit tests
        run: dotnet test ${{ matrix.test-projects }}
