name: .NET Core Desktop Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ShuftManager.sln                               # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: ShiftManager.Test/ShiftManager.Test.csproj # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: Release

    - name: Create the app package (x64)
      run: dotnet publish ShiftManager/ShiftManager.csproj -c Release -f net5.0-windows -o pubX64 -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -r win-x64
      
    - name: Create the app package (x86)
      run: dotnet publish ShiftManager/ShiftManager.csproj -c Release -f net5.0-windows -o pubX86 -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -r win-x86

    - name: Upload build artifacts (X64)
      uses: actions/upload-artifact@v2
      with:
        name: Package_X64
        path: ShiftManager\pubX64

    - name: Upload build artifacts (X86)
      uses: actions/upload-artifact@v2
      with:
        name: Package_X64
        path: ShiftManager\pubX86
